"""Add roles and users_roles tables

Revision ID: 008d7ca46383
Revises: ef3aff14af35
Create Date: 2025-08-18 13:07:25.178068

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "008d7ca46383"
down_revision = "ef3aff14af35"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("role_name", sa.String(length=80), nullable=False),
        sa.Column("department_name", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("role_id"),
        sa.UniqueConstraint(
            "role_name", "department_name", name="uq_role_name_department"
        ),
    )
    op.create_table(
        "users_roles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.role_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_roles")
    op.drop_table("roles")
    # ### end Alembic commands ###
