"""Add status field to User

Revision ID: 4419892819e6
Revises: f294331aa713
Create Date: 2025-08-17 21:02:42.412549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4419892819e6'
down_revision = 'f294331aa713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='userstatusenum'), nullable=False, server_default='INACTIVE'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
