"""Add profile_id to the User table

Revision ID: b7984618099d
Revises: 9a0d7da8fb4f
Create Date: 2025-09-03 12:21:42.809073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b7984618099d"
down_revision = "9a0d7da8fb4f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("public_id", sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ["public_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("public_id")

    # ### end Alembic commands ###
