"""Update User table to store hashed password

Revision ID: bb1fb568c0ed
Revises: b7984618099d
Create Date: 2025-09-03 12:25:59.387179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bb1fb568c0ed"
down_revision = "b7984618099d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.VARCHAR(length=128),
            type_=sa.String(length=500),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.String(length=500),
            type_=sa.VARCHAR(length=128),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
