"""Add inactive_data field to user table

Revision ID: ef3aff14af35
Revises: 4419892819e6
Create Date: 2025-08-18 10:14:31.326677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef3aff14af35"
down_revision = "4419892819e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("inactive_date", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("inactive_date")

    # ### end Alembic commands ###
